packaging_format = 2

id = "xwiki"
name = "XWiki"
description.en = "Collaboration tool based on the wiki principle"
description.fr = "Outil de collaboration basé sur le principe du wiki"

version = "16.5.0~ynh1"

maintainers = ["Josué Tille"]

[upstream]
license = "LGPL-2.1"
website = "https://www.xwiki.org/"
demo = "https://playground.xwiki.org/xwiki/bin/view/Main/WebHome"
admindoc = "https://www.xwiki.org/xwiki/bin/view/Documentation/AdminGuide/"
userdoc = "https://www.xwiki.org/xwiki/bin/view/Documentation/UserGuide/"
code = "https://github.com/xwiki/xwiki-platform"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

ldap = true

sso = false

disk = "500M"
ram.build = "0M"
ram.runtime = "1G"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/xwiki"

    [install.install_standard_flavor]
    ask.en = "Would you like to install the Standard Flavor?"
    help.en = "See https://extensions.xwiki.org/xwiki/bin/view/Extension/XWiki%20Standard%20Flavor/ for more informations."
    type = "boolean"
    default = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.init_admin_permission]
    ask.en = "Which group will have access to xWiki admin page"
    ask.fr = "Quel groupe aura accès à l'administration de xWiki"
    help.en = "Users of this group should have access to xWiki admin page"
    help.fr = "Les utilisateurs de ce groupe devrait avoir accès à la page d'administration de xWiki"
    type = "group"
    default = "admins"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://nexus.xwiki.org/nexus/content/groups/public/org/xwiki/platform/xwiki-platform-distribution-jetty-hsqldb/16.5.0/xwiki-platform-distribution-jetty-hsqldb-16.5.0.zip"
        sha256 = "d57f261fc163b9747ffc16704e6663b0509fbbed0a9cd28f772578fad9679012"
        format = "zip"

        [resources.sources.jdbc]
        url = "https://jdbc.postgresql.org/download/postgresql-42.7.3.jar"
        rename = "postgresql-42.7.3.jar"
        sha256 = "a2644cbfba1baa145ff7e8c8ef582a6eed7a7ec4ca792f7f054122bdec756268"

        # Note that xq is available on debian package since debian 12
        # So on bookworm should just remove this and use official package
        [resources.sources.xq_tool]
        in_subdir= false

        i386.url = "https://github.com/sibprogrammer/xq/releases/download/v1.2.4/xq_1.2.4_linux_386.tar.gz"
        i386.sha256 = "f51e27493fb49dee53f3511ad6f4710f8fb7014e6ba0796d3c6d2eee6ceef914"

        amd64.url = "https://github.com/sibprogrammer/xq/releases/download/v1.2.4/xq_1.2.4_linux_amd64.tar.gz"
        amd64.sha256 = "96148dc3ce4fede9ab47b26fa07f1ada950dfd61ae54db7013c76a410945302f"

        armhf.url = "https://github.com/sibprogrammer/xq/releases/download/v1.2.4/xq_1.2.4_linux_armv7.tar.gz"
        armhf.sha256 = "9b08c33f1a3dd1f7a6a82dd91ef7dfb5297d0c3ea2ccfc6ee616393667862d56"

        arm64.url = "https://github.com/sibprogrammer/xq/releases/download/v1.2.4/xq_1.2.4_linux_arm64.tar.gz"
        arm64.sha256 = "414ea9fde3c6e669f034465c21aa095bc3c10a3e3dd8c2989ee8073605274bf9"

        #
        # INFO need also to update extensions version on _common.sh
        #

    [resources.ports]
    main.default = 8080

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    dir = "/opt/yunohost/__APP__"

    [resources.data_dir]
    dir = "/home/yunohost.app/__APP__"

    [resources.permissions]
    main.url = "/"

    admin.label = "Admins"

    [resources.apt]
    packages = ["openjdk-17-jre", "postgresql", "libreoffice"]

    [resources.database]
    type = "postgresql"
